prompt: "Complete the mirror reflection realistically and consistently with the scene geometry."
negative_prompt: "negative_prompt"
edit_model_prompt_template: "Fill in the mirror which corresponds to the mask. The prompt describing the image is: {prompt}"
edit_models:
  - "Qwen/Qwen-Image-Edit-2511"
default_output_path: "outputs/result.png"
blender_path: "external/blender/blender-4.4.3-linux-x64/blender"
geometry_model_name: "Ruicheng/moge-2-vitl-normal"
# geometry_model_name: "depth-anything/DA3NESTED-GIANT-LARGE-1.1"
inpainting_model_name: "black-forest-labs/FLUX.1-Fill-dev"
# inpainting_model_name: "Qwen/Qwen-Image-Edit"
hf_dataset_repo: "OfekBassonResearch/Fill-My-Mirror"
hf_blender_dataset_repo: "OfekBassonResearch/Fill-My-Mirror-Blender"
mast3r_model_name: "naver/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric"
